### ISSUE TITLE
Freeplace

### ISSUE THREAD

**Issue by Xevi8X** [PW-MiNI-IO2-2023-Group-3/Specyfikacja#10]
Rozróżnić wszystkie wolne miejsca od jeszcze wolnych miejsc

**Comment by Mattioo7** [comment]
Mogę poprosić o wytłumaczenie?

**Comment by Xevi8X** [comment]
Oczywiście.

Z punktu widzenia organizora (web panelu) ważne są dwie informacje: ile jest jeszcze wolnych miejsc na utworzony przez niego event, oraz ile wolnych miejsc w sumie zadeklarował jako organizator. Mamy system patchowania eventów, który pozwala organizatorowi np zwiększyć liczbę wolnych miejsc (dokupił krzesła czy cos). Skąd jednak system ma wiedzieć ile zadeklarował poprzednio skoro zwortka zawiera tylko liczbę aktualnie dostępnych?

Uważam że należy do obiektu DTO jakim jest event dodać pole maxPlace, zawierające tą informację. Wisi nad nami również zmiana systemu schematu i zwracania informacji. Może warto połączyć to w jedną zmianę.

Podsumowując proponuje następującą:
Obiekt EventDto dostanie nowe pola:
- maxPlace: integer - całkowita liczba wolnych miejsc
-places: array obiektów Place

gdzie Place zawiera pola:
- no: integer - numer miejsca
- free: bool - określa czy miejsce jest wolne

**Comment by Xevi8X** [comment]
```yaml
Event:
      required:
        - id
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        title:
          type: string
          example: Short description of Event
        startTime:
          type: integer
          format: int64
          example: 1673034164
        endTime:
          type: integer
          format: int64
          example: 1683034164
        latitude:
          type: string
          example: '40.4775315'
        longitude:
          type: string
          example: '-3.7051359'
        name:
          type: string
          example: Long description of Event
        placeSchema:
          type: string
          example: Seralized place schema
        status:
          $ref: '#/components/schemas/EventStatus'
        categories:
          type: array
          items:
            $ref: '#/components/schemas/Category'
# POCZATEK ZMIAN
        freePlace:
          type: integer
          format: int64
          example: 2
        maxPlace:
          type: integer
          format: int64
          example: 100
        places:
          type: array
          items:
            $ref: '#/components/schemas/Place'
          
    Place:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 21
        free:
          type: boolean
          example: true
# KONIEC ZMIAN
```
