### ISSUE TITLE
Miejsce eventu

### ISSUE THREAD

**Issue by Mattioo7** [PW-MiNI-IO2-2023-Group-3/Specyfikacja#5]
Swagger nie zawiera żadnych informacji nt. przysyłania czy przechowywania miejsca eventu. Proponuję przechowywanie miejsca jako współrzędne.

**Comment by Xevi8X** [comment]
Zgadza się, nie zostało to ujęte w API. Trzeba zmodyfikować DTO Event. Jaką formę przechowywania współrzędnych proponujesz?

**Comment by Mattioo7** [comment]
szerokość, długość
Analogicznie jak np. na google maps: 40.477531598342985, -3.705135931357368 = Madryt

**Comment by Xevi8X** [comment]
jako floaty?

**Comment by Mattioo7** [comment]
Proponuję jako string z dokładnością liczb do 7 miejsca po przecinku, ale nie ma to aż takiego znaczenia

**Comment by Xevi8X** [comment]
Dla mnie ok. Jako, że zostałem uprawniony do podejmowania decyzji w imieniu grupy, cała moja grupa zgadza się na ten pomysł. Czekam na aprobatę pozostałych zespołów i zabiorę się do wprowadzenia zmian.
