### ISSUE TITLE
Missing status of organizer

### ISSUE THREAD

**Issue by Xevi8X** [PW-MiNI-IO2-2023-Group-3/Specyfikacja#9]
https://github.com/PW-MiNI-IO2-2023-Group-3/Specyfikacja/blob/119ab64d4e24ee382a8e398ad6cd67e556672071/API.json#L850-L853

missing "deleted" status of Organizer.

**Comment by adamdab** [comment]
Czemu mamy mieć w bazie danych Organizatorów już nie istniejących ?

**Comment by Xevi8X** [comment]
To jest standardowy mechanizm zachowania koherencji bazy. Bez organizatora nie ma eventy, itd. żeby nie usuwać pół bazy dane organizatora utajnia się (np. hashuje), encja zostaje w bazie.

**Comment by Xevi8X** [comment]
Ale teraz pomyślałem że ta informacja nie musi być zwracana więc api tego nie dotyczy.
